version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product_db
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  nacos:
    image: nacos/nacos-server:latest
    ports:
      - "8848:8848"

  product-service:
    image: product-service:latest
    depends_on:
      - mysql
      - redis
      - nacos
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/product_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  inventory-service:
    image: inventory-service:latest
    depends_on:
      - nacos
    ports:
      - "8082:8082"
